// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjnYTbkMjltty6j8MestEQXH9tznObqY',
    appId: '1:712137951046:web:819cafc870589527fd0747',
    messagingSenderId: '712137951046',
    projectId: 'rememberme-1edf1',
    authDomain: 'rememberme-1edf1.firebaseapp.com',
    storageBucket: 'rememberme-1edf1.appspot.com',
    measurementId: 'G-S3FPNC2MLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlE0oNukQ90phy6m8Yz2Hc6FVLiilJAOs',
    appId: '1:712137951046:android:3da1fe9ca2beaaacfd0747',
    messagingSenderId: '712137951046',
    projectId: 'rememberme-1edf1',
    storageBucket: 'rememberme-1edf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1CO3lL5QUW5WLw_fKJBPgowJ67ec9-Ok',
    appId: '1:712137951046:ios:2d513b20cd24394afd0747',
    messagingSenderId: '712137951046',
    projectId: 'rememberme-1edf1',
    storageBucket: 'rememberme-1edf1.appspot.com',
    iosClientId: '712137951046-oa9c60b1lu06sql3jgijphmvfpvjaba3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rememberMeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1CO3lL5QUW5WLw_fKJBPgowJ67ec9-Ok',
    appId: '1:712137951046:ios:2d513b20cd24394afd0747',
    messagingSenderId: '712137951046',
    projectId: 'rememberme-1edf1',
    storageBucket: 'rememberme-1edf1.appspot.com',
    iosClientId: '712137951046-oa9c60b1lu06sql3jgijphmvfpvjaba3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rememberMeMobile',
  );
}
