// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeAFR7IEzcGRg7GKaHU_2EEDToNOxE4Os',
    appId: '1:149391822612:web:3763b9d94b87cda677bc01',
    messagingSenderId: '149391822612',
    projectId: 'fcm-test-333c6',
    authDomain: 'fcm-test-333c6.firebaseapp.com',
    storageBucket: 'fcm-test-333c6.appspot.com',
    measurementId: 'G-C3GZ7FWF7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRqPHL5FqyKhMwk-P4Vl32aptTHA3z3E0',
    appId: '1:149391822612:android:c80312d7e47dfe4677bc01',
    messagingSenderId: '149391822612',
    projectId: 'fcm-test-333c6',
    storageBucket: 'fcm-test-333c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ekqGix3Glk-MuJkiX2rB0foMNcLkr2I',
    appId: '1:149391822612:ios:f7f481fcaa46acd977bc01',
    messagingSenderId: '149391822612',
    projectId: 'fcm-test-333c6',
    storageBucket: 'fcm-test-333c6.appspot.com',
    iosClientId: '149391822612-hniqdrklrubmld4alkhslfal1idd7adt.apps.googleusercontent.com',
    iosBundleId: 'com.example.rememberMeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ekqGix3Glk-MuJkiX2rB0foMNcLkr2I',
    appId: '1:149391822612:ios:f7f481fcaa46acd977bc01',
    messagingSenderId: '149391822612',
    projectId: 'fcm-test-333c6',
    storageBucket: 'fcm-test-333c6.appspot.com',
    iosClientId: '149391822612-hniqdrklrubmld4alkhslfal1idd7adt.apps.googleusercontent.com',
    iosBundleId: 'com.example.rememberMeMobile',
  );
}
